### PR TITLE
Allow password protection to be controlled via the site

### PR DESCRIPTION
**Pull request by mikestreety**
Once again, thanks for a handy extension!

**This MR is a breaking change**

Rather than assume all sites are password protected when the password is present, this enables configuration via the Site config file and so allows you to disable/enable depending on environment - especially useful in a multi-site setup.

**Site note:** If you no longer wish to maintain this package then I would be happy to adopt it

### CODE REVIEW

**Comment by r12r** [comment]
Hi Mike!

Many thanks for your work!
I will have a look at the request this weekend and try to create a version that is compatible with previous installations.

Best wishes - Bastian

**Comment by mikestreety** [comment]
@r12r Great thanks,

I have only tested this on TYPO3 version 10

**Comment by mikestreety** [comment]
@r12r Hey Bastian, any luck with this? (sorry to hassle)

**Comment by mikestreety** [comment]
@r12r Hey, any thoughts on this? I'm happy to help out with maintenance if you don't have the time/inclination. We use this on most of our projects now :)

**Comment by r12r** [comment]
@mikestreety 

Hi Mike. Yes, your help would be greatly appreciated!  If it's ok with you, I can add you as a maintainer to the repository. 
I would be happy to hear from you!

**Comment by mikestreety** [comment]
More than happy to be a contributor 👍

**Comment by r12r** [comment]
hi mike, sorry for the long delay. Unfortunately, I don't have any time to look at the pull request. I've added you to the repo as a maintainer. If you want, you can merge the request.
Best - Bastian

**Pull request merged**
